M48
; DRILL file {KiCad 7.0.7} date Wed Sep  6 15:28:25 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-06T15:28:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0276
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0492
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0906
%
G90
G05
T1
X4.3386Y-4.4567
X4.3886Y-4.4567
X4.4386Y-4.4567
X4.4886Y-4.4567
X4.5386Y-4.4567
T2
X5.8177Y-4.6146
X5.8177Y-4.7917
T3
X4.1016Y-4.4437
X4.1016Y-4.961
T0
M30
